services:
  - type: web
    name: logistik-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false   # set manually in Render dashboard
      - key: JwtSettings__SecretKey
        sync: false   # set manually in Render dashboard
